version: '3.5'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HTTP_PORT_EXTERNAL}:80
      - ${NGINX_HTTPS_PORT_EXTERNAL}:443
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf:/etc/nginx/conf.d/
      - ../app:${APP_BASE_PATH}
    links:
     - php

  php:
    env_file:
      - .env
    build:
      context: php
    volumes:
      - ../app:${APP_BASE_PATH}